version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command:
      [
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "app.main:app",
        "--reload",
      ]
    networks:
      - app-net
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: redis-server --save 10 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - app-net
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: on-failure
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-net
volumes:
  cache:
    driver: local
networks:
  app-net:

